spring:
    cloud:
        sentinel:
            transport:
                # Sentinel 控制台地址
                dashboard: localhost:8858
                # 如果有多套网络，又无法正确获取本机IP，则需要使用下面的参数设置当前机器可被外部访问的IP地址，供admin控制台使用
#                client-ip: ''
            # 取消Sentinel控制台懒加载
            # 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
            # 配置 sentinel.eager=true 时，取消Sentinel控制台懒加载功能
            eager: true
            # 禁止收敛URL的入口context
            # Sentinel Web filter 默认收敛所有URL的入口context，会造成链路限流不生效。
            web-context-unify: false
            datasource:
                flow-rule:
                    nacos:
                        rule-type: flow
                        server-addr: 127.0.0.1:8848
                        group-id: ${spring.application.name}
                        data-id: sentinel-rule:flow