#项目运行配置环境
server:
  port: 8080
spring:
  application:
    name: spring-cloud-alibaba-demo
  config:
    import: classpath:dubbo.properties
  profiles:
    active: dev
    include: sentinel
logging:
  level:
    root: info
